export const INTERFACE_NAME = {
  UserRepository: Symbol.for('UserRepository'),
  UserService: Symbol.for('UserService'),
  UserController: Symbol.for('UserController'),
  AuthService: Symbol.for('AuthService'),
  AuthController: Symbol.for('AuthController'),
  Mailer: Symbol.for('Mailer'),
  MessageBroker: Symbol.for('MessageBroker'),
  AddressRepository: Symbol.for('AddressRepository'),
  AddressService: Symbol.for('AddressService'),
  AddressController: Symbol.for('AddressController'),
  CustomerRepository: Symbol.for('CustomerRepository'),
  CustomerService: Symbol.for('CustomerService'),
  AdminRepository: Symbol.for('AdminRepository'),
  AdminService: Symbol.for('AdminService'),
};
